username: "thilinama@wso2.com"
password: ""
email: "thilinama@wso2.com"

namespace: "wso2"
svcaccount: "wso2svc-account"
serverIp: "10.128.0.6"
sharedDeploymentLocationPath: "/data/is/deployment"
sharedTentsLocationPath: "/data/is/tenants"
